language: objective-c
osx_image: xcode7.31
xcode_sdk: iphonesimulator9.3
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --platform iOS
script: 
- xcodebuild -project BeerUp.xcodeproj -sdk iphonesimulator ONLY_ACTIVE=NO
- xctool test -project BeerUp.xcodeproj -scheme BeerUp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
