language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
env:
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before script:
  - carthage build --platform iOS
script: 
- xcodebuild -project BeerUp.xcodeproj -sdk iphonesimulator ONLY_ACTIVE=NO
- xctool test -project BeerUp.xcodeproj -scheme BeerUp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
