language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
script: 
- xcodebuild -project BeerUp.xcodeproj -sdk iphonesimulator ONLY_ACTIVE=NO
- xctool test -project BeerUp.xcodeproj -scheme BeerUp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
