language: objective-c
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2
script: 
- xcodebuild -project BeerUp.xcodeproj -sdk iphonesimulator ONLY_ACTIVE=NO
- xctool test -project BeerUp.xcodeproj -scheme BeerUp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
